[package]
name = "slack-open"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "so"
path = "src/main.rs"

[dependencies]
# Error handling
anyhow = "1.0.93"

# Command line parsing
clap = { version = "4.5.21", features = ["derive"] }

# Open URI
open = "5.3.1"

# Ser/de
serde = { version = "1.0.215", features = ["derive"] }
skim = "0.13.0"
toml = "0.8.19"

# Configuration directory
xdg = "2.5.2"
